export const issues = [
  {
    id: 1,
    category: "Waste Management",
    description: "Overflowing garbage bins near the main road ",
    status: "open",
    latitude: 28.6139,
    longitude: 77.209,
    area: "Connaught Place",
    city: "Delhi",
    created_at: "2025-01-05T10:15:00Z",
    user: { id: 101, name: "Rahul Sharma", role: "citizen" },
  },
  {
    id: 2,
    category: "Water",
    description: "Water leakage causing road damage",
    status: "in_progress",
    latitude: 19.076,
    longitude: 72.8777,
    area: "Andheri East",
    city: "Mumbai",
    created_at: "2025-01-06T09:40:00Z",
    user: { id: 102, name: "Neha Verma", role: "citizen" },
  },
  {
    id: 3,
    category: "Roads",
    description: "Large pothole near school entrance",
    status: "open",
    latitude: 12.9716,
    longitude: 77.5946,
    area: "Indiranagar",
    city: "Bangalore",
    created_at: "2025-01-06T14:20:00Z",
    user: { id: 103, name: "Amit Patel", role: "citizen" },
  },
  {
    id: 4,
    category: "Water",
    description: "Street lights not working for last 5 days",
    status: "resolved",
    latitude: 17.385,
    longitude: 78.4867,
    area: "Banjara Hills",
    city: "Hyderabad",
    created_at: "2025-01-07T18:05:00Z",
    user: { id: 104, name: "Sneha Reddy", role: "citizen" },
  },
  {
    id: 5,
    category: "Roads",
    description: "Public toilet not cleaned regularly",
    status: "open",
    latitude: 26.9124,
    longitude: 75.7873,
    area: "Malviya Nagar",
    city: "Jaipur",
    created_at: "2025-01-08T07:55:00Z",
    user: { id: 105, name: "Rohit Jain", role: "citizen" },
  },
  {
    id: 6,
    category: "Water",
    description: "Signal malfunction causing traffic jams",
    status: "in_progress",
    latitude: 22.5726,
    longitude: 88.3639,
    area: "Salt Lake",
    city: "Kolkata",
    created_at: "2025-01-08T16:30:00Z",
    user: { id: 106, name: "Ananya Das", role: "citizen" },
  },
  {
    id: 7,
    category: "Waste Management",
    description: "Illegal dumping behind residential colony",
    status: "open",
    latitude: 23.0225,
    longitude: 72.5714,
    area: "Maninagar",
    city: "Ahmedabad",
    created_at: "2025-01-09T11:10:00Z",
    user: { id: 107, name: "Kunal Mehta", role: "citizen" },
  },
  {
    id: 8,
    category: "Water",
    description: "Low water pressure in the morning hours",
    status: "open",
    latitude: 18.5204,
    longitude: 73.8567,
    area: "Kothrud",
    city: "Pune",
    created_at: "2025-01-09T06:45:00Z",
    user: { id: 108, name: "Pooja Kulkarni", role: "citizen" },
  },
  {
    id: 9,
    category: "Roads",
    description: "Broken footpath causing inconvenience to pedestrians",
    status: "in_progress",
    latitude: 21.1702,
    longitude: 72.8311,
    area: "Adajan",
    city: "Surat",
    created_at: "2025-01-10T13:00:00Z",
    user: { id: 109, name: "Vikas Shah", role: "citizen" },
  },
  {
    id: 10,
    category: "Roads",
    description: "Frequent power cuts during evening hours",
    status: "open",
    latitude: 25.5941,
    longitude: 85.1376,
    area: "Kankarbagh",
    city: "Patna",
    created_at: "2025-01-10T19:25:00Z",
    user: { id: 110, name: "Suman Kumar", role: "citizen" },
  },
  {
    id: 11,
    category: "Water",
    description: "Open drain emitting foul smell",
    status: "open",
    latitude: 26.8467,
    longitude: 80.9462,
    area: "Alambagh",
    city: "Lucknow",
    created_at: "2025-01-11T08:15:00Z",
    user: { id: 111, name: "Farhan Ali", role: "citizen" },
  },
  {
    id: 12,
    category: "Waste Management",
    description: "No zebra crossing near busy intersection",
    status: "open",
    latitude: 30.7333,
    longitude: 76.7794,
    area: "Sector 17",
    city: "Chandigarh",
    created_at: "2025-01-11T17:40:00Z",
    user: { id: 112, name: "Simran Kaur", role: "citizen" },
  },
  {
    id: 13,
    category: "Waste Management",
    description: "Garbage collection truck skips area frequently",
    status: "in_progress",
    latitude: 11.0168,
    longitude: 76.9558,
    area: "RS Puram",
    city: "Coimbatore",
    created_at: "2025-01-12T09:50:00Z",
    user: { id: 113, name: "Arjun Nair", role: "citizen" },
  },
  {
    id: 14,
    category: "Water",
    description: "Contaminated water supply reported",
    status: "resolved",
    latitude: 9.9312,
    longitude: 76.2673,
    area: "Kaloor",
    city: "Kochi",
    created_at: "2025-01-12T15:05:00Z",
    user: { id: 114, name: "Meera Menon", role: "citizen" },
  },
  {
    id: 15,
    category: "Roads",
    description: "Unmarked speed breaker causing accidents",
    status: "open",
    latitude: 28.7041,
    longitude: 77.1025,
    area: "Rohini",
    city: "Delhi",
    created_at: "2025-01-13T21:10:00Z",
    user: { id: 115, name: "Deepak Yadav", role: "citizen" },
  },
];
